[permission]
user = "user"
group = "group"
acl_list = []
default_permission = []
writable_paths = []

[command_hook]
post_release = "exit 1"
pre_symlink = "echo Default pre_symlink"
post_symlink = "echo Default post_symlink"
start = "echo Default start"
