[permission]
# user = "www-data"
# group = "www-data"
acl_list = []
default_permission = []
writable_paths = []

[command_hooks]
post_release = "echo post_release"
pre_symlink = "echo pre_symlink"
post_symlink = "echo post_symlink"
start = "echo start"
